package com.github.valeryad.entities;

public enum Subjects {
    MATHEMATICAL_ANALYSIS, ALGEBRA, GEOMETRY, PROGRAMMING, COMPUTER_NETWORKS,
    FOREIGN_LANGUAGE, WORLD_HISTORY, HISTORY_OF_BELARUS, INTERNATIONAL_MARKETING, THEORY_AND_PRACTICE_OF_INTERCULTURAL_COMMUNICATIONS,
    GENERAL_THEORY_OF_LAW, CIVIL_LAW, CRIMINAL_LAW, ECONOMIC_LAW, CRIMINOLOGY

}
