package com.github.valeryad.entities;

public enum Subjects {
    MATHEMATICAL_ANALYSIS, ALGEBRA, GEOMETRY, PROGRAMMING, COMPUTER_NETWORKS,             //Faculty of Applied Mathematics and Computer Science
    FOREIGN_LANGUAGE, WORLD_HISTORY, HISTORY_OF_BELARUS, INTERNATIONAL_MARKETING, THEORY_AND_PRACTICE_OF_INTERCULTURAL_COMMUNICATIONS,  //Faculty of History
    GENERAL_THEORY_OF_LAW, CIVIL_LAW, CRIMINAL_LAW, ECONOMIC_LAW, CRIMINOLOGY             //Faculty of law

}
